from cwr_webclient.service.cwr_service import WSCWRService
from cwr_webclient.service.appinfo import WESOApplicationInfoService
from cwr_webclient.service.pagination import DefaultPaginationService
from cwr_webclient.service.report import MeraReportService, CWRReportService
